# CA05 kNN Recommender

Team 5: Mathia Quimpo, Matthew Chin

## Data Source and Contents

In [1]:
# import necessary libraries
import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors

In [2]:
# load dataset
movies_data = pd.read_csv('https://github.com/ArinB/MSBA-CA-Data/raw/main/CA05/movies_recommendation_data.csv')
movies_data

,Movie ID,Movie Name,IMDB Rating,Biography,Drama,Thriller,Comedy,Crime,Mystery,History,Label
0,58,The Imitation Game,8.0,1,1,1,0,0,0,0,0
1,8,Ex Machina,7.7,0,1,0,0,0,1,0,0
2,46,A Beautiful Mind,8.2,1,1,0,0,0,0,0,0
3,62,Good Will Hunting,8.3,0,1,0,0,0,0,0,0
4,97,Forrest Gump,8.8,0,1,0,0,0,0,0,0
5,98,21,6.8,0,1,0,0,1,0,1,0
6,31,Gifted,7.6,0,1,0,0,0,0,0,0
7,3,Travelling Salesman,5.9,0,1,0,0,0,1,0,0
8,51,Avatar,7.9,0,0,0,0,0,0,0,0
9,47,The Karate Kid,7.2,0,1,0,0,0,0,0,0
10,50,A Brilliant Young Mind,7.2,0,1,0,0,0,0,0,0
11,49,A Time To Kill,7.4,0,1,1,0,1,0,0,0
12,30,Interstellar,8.6,0,1,0,0,0,0,0,0
13,94,The Wolf of Wall Street,8.2,1,0,0,1,1,0,0,0
14,6,Black Panther,7.4,0,0,0,0,0,0,0,0
15,73,Inception,8.8,0,0,0,0,0,0,0,0
16,44,The Wind Rises,7.8,1,1,0,0,0,0,0,0
17,65,Spirited Away,8.6,0,0,0,0,0,0,0,0
18,48,Finding Forrester,7.3,0,1,0,0,0,0,0,0
19,27,The Fountain,7.3,0,0,0,0,0,0,0,0
20,57,The DaVinci Code,6.6,0,0,1,0,0,1,0,0
21,57,Stand and Deliver,7.3,0,1,0,0,0,0,0,0
22,14,The Terminator,8.0,0,0,0,0,0,0,0,0
23,69,21 Jump Street,7.2,0,0,0,1,1,0,0,0
24,98,The Avengers,8.1,0,0,0,0,0,0,0,0
25,17,Thor: Ragnarok,7.9,0,0,0,1,0,0,0,0
26,12,Spirit: Stallion of the Cimarron,7.1,0,0,0,0,0,0,0,0
27,1,Hacksaw Ridge,8.2,1,1,0,0,0,0,1,0
28,86,12 Years a Slave,8.1,1,1,0,0,0,0,1,0
29,46,Queen of Katwe,7.4,1,1,0,0,0,0,0,0

## Building Recommender System

In [3]:
# convert dataset to dictionary with titles as keys
movies_dict = movies_data.set_index('Movie Name').to_dict(orient='index')

# extract movie titles from dictionary
movies_titles = list(movies_dict.keys())

In [4]:
# select columns to train model
train_columns = ['IMDB Rating', 
                   'Biography',
                   'Drama', 
                   'Thriller', 
                   'Comedy',
                   'Crime',
                   'Mystery', 
                   'History']

x_train = movies_data[train_columns]
x_train

    IMDB Rating  Biography  Drama  Thriller  Comedy  Crime  Mystery  History
0           8.0          1      1         1       0      0        0        0
1           7.7          0      1         0       0      0        1        0
2           8.2          1      1         0       0      0        0        0
3           8.3          0      1         0       0      0        0        0
4           8.8          0      1         0       0      0        0        0
5           6.8          0      1         0       0      1        0        1
6           7.6          0      1         0       0      0        0        0
7           5.9          0      1         0       0      0        1        0
8           7.9          0      0         0       0      0        0        0
9           7.2          0      1         0       0      0        0        0
10          7.2          0      1         0       0      0        0        0
11          7.4          0      1         1       0      1        0        0
12          8.6          0      1         0       0      0        0        0
13          8.2          1      0         0       1      1        0        0
14          7.4          0      0         0       0      0        0        0
15          8.8          0      0         0       0      0        0        0
16          7.8          1      1         0       0      0        0        0
17          8.6          0      0         0       0      0        0        0
18          7.3          0      1         0       0      0        0        0
19          7.3          0      0         0       0      0        0        0
20          6.6          0      0         1       0      0        1        0
21          7.3          0      1         0       0      0        0        0
22          8.0          0      0         0       0      0        0        0
23          7.2          0      0         0       1      1        0        0
24          8.1          0      0         0       0      0        0        0
25          7.9          0      0         0       1      0        0        0
26          7.1          0      0         0       0      0        0        0
27          8.2          1      1         0       0      0        0        1
28          8.1          1      1         0       0      0        0        1
29          7.4          1      1         0       0      0        0        0

In [5]:
# build nearest neighbors model
neigh = NearestNeighbors(n_neighbors=5)
model = neigh.fit(x_train)

## Test the model

In [6]:
# create dataframe for test movie "The Post"
the_post = pd.DataFrame({'IMDB Rating':[7.2], 
                         'Biography':[1], 
                         'Drama':[1], 
                         'Thriller':[0], 
                         'Comedy':[0], 
                         'Crime':[0], 
                         'Mystery':[0], 
                         'History':[1]})

# first array contains distances of the recommended movie, second array contains index of the recommended movie
rec_distances, rec_indices = model.kneighbors(the_post)

## Print the Results

In [7]:
# print results
print("More Movies Like \"The Post\":")

# loop through indexes and print the associated movie title
for i, idx in enumerate(rec_indices[0]):
    print(f"{movies_titles[idx]} (Distance = {rec_distances[0][i]})")

More Movies Like "The Post":
12 Years a Slave (Distance = 0.8999999999999995)
Hacksaw Ridge (Distance = 0.9999999999999991)
Queen of Katwe (Distance = 1.019803902718557)
The Wind Rises (Distance = 1.16619037896906)
A Beautiful Mind (Distance = 1.4142135623730945)